<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Project time</string>
	<key>fileTypes</key>
	<array>
		<string>time</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(def|class)\s+([.a-zA-Z0-9_ &lt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>.*:(?!\d\d)</string>
			<key>name</key>
			<string>keyword.control.issue</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>all.time</string>
	<key>uuid</key>
	<string>c1c8b6dd-ec78-4553-99d0-d405152f9eed</string>
</dict>
</plist>
